# Generated by Django 5.1 on 2024-08-11 20:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('battery', models.IntegerField()),
                ('wifi', models.CharField(max_length=40)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='phones.phone')),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Locations History',
                'ordering': ['id'],
            },
        ),
    ]
